<a href="https://colab.research.google.com/github/anjithababuraj/Projects/blob/main/allmodelheart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/heart_missing (1).csv')
df

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.dtypes

In [ ]:
df.isna().sum()

In [ ]:
df1=df.groupby('target') ['target'].count() #to check balanced or imbalanced
df1

target
0    499
1    526
Name: target, dtype: int64

In [ ]:
p=df['cp'].mean()
df['cp'].fillna(p,inplace=True)
q=df['fbs'].mean()
df['fbs'].fillna(q,inplace=True)
r=df['restecg'].mean()
df['restecg'].fillna(r,inplace=True)
s=df['oldpeak'].mean()
df['oldpeak'].fillna(s,inplace=True)

In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
k_model=KNeighborsClassifier(n_neighbors=7)
n_model=GaussianNB()
s_model=SVC()
lst_model=[k_model,n_model,s_model]

In [ ]:
for i in lst_model:
  print("Model name:",i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print(confusion_matrix(y_test,y_pred))
  print(accuracy_score(y_test,y_pred))
  print("*********************************")

Model name: KNeighborsClassifier(n_neighbors=7)
[[127  32]
 [ 16 133]]
0.8441558441558441
*********************************
Model name: GaussianNB()
[[119  40]
 [ 19 130]]
0.8084415584415584
*********************************
Model name: SVC()
[[134  25]
 [ 11 138]]
0.8831168831168831
*********************************
